export const DEFAULT_GATEWAY_HOST = '127.0.0.1';
export const DEFAULT_GATEWAY_PORT = 8024;
export const DEFAULT_GATEWAY_BASE_URL = `http://${DEFAULT_GATEWAY_HOST}:${DEFAULT_GATEWAY_PORT}`;
export const TOKEN_HEADER = 'X-CWMB-Token';
export const MAX_INSERTED_CHARS = 60_000;
